source = ~/.config/hypr/conf/decoration.conf #Animations 

source = ~/.config/hypr/conf/envs.conf # Environment Variables

source = ~/.config/hypr/conf/keybindings.conf # keybindings

source = ~/.config/hypr/conf/monitors.conf # Monitor settings

source = ~/.config/hypr/conf/rules.conf #windows rules

source = ~/.config/hypr/conf/startup.conf #exec-once apps